# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
- name: token
  type: string

steps:
- script: |
    dotnet test tests
  displayName: ✅  Test

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker publish \
          pacts \
        --version ${GIT_COMMIT} \
        --branch ${GIT_BRANCH} \
        --build-url ${BUILD_URI}
  displayName: ✉️  Publish Pacts
  env:
    PACT_BROKER_BASE_URL: https://testdemo.pactflow.io
    PACT_BROKER_TOKEN: ${{ parameters.token }}
    GIT_COMMIT: $(Build.SourceVersion)
    GIT_BRANCH: $(Build.SourceBranchName)
    BUILD_URI: '$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker can-i-deploy \
        --pacticipant ${PACTICIPANT} \
        --version ${GIT_COMMIT} \
        --to-environment production
  displayName: 🎛  Can I deploy?
  env:
    PACT_BROKER_BASE_URL: https://testdemo.pactflow.io
    PACT_BROKER_TOKEN: ${{ parameters.token }}
    GIT_COMMIT: $(Build.SourceVersion)
    PACTICIPANT: "pactflow-example-consumer-dotnet"

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker record_deployment \
          --pacticipant ${PACTICIPANT} \
          --version ${GIT_COMMIT} \
          --environment production
  displayName: 🚀  Deploy
  env:
    PACT_BROKER_BASE_URL: https://testdemo.pactflow.io
    PACT_BROKER_TOKEN: ${{ parameters.token }}
    GIT_COMMIT: $(Build.SourceVersion)
    PACTICIPANT: "pactflow-example-consumer-dotnet"
