# Pact consumer workflow
# Test (Generate pacts) -> Publish pacts -> Can-I-Deploy to Prod (with Polling) -> Record Deployment (master branch)
# Webhooks are setup for provider, to trigger on contract_requiring_verification_published

pool:
  vmImage: ubuntu-latest

variables:
  - name: PACTICIPANT
    value: "pactflow-example-consumer-dotnet"
  - name: PACT_BROKER_BASE_URL
    value: https://testdemo.pactflow.io
  - name: GIT_BRANCH
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  - name: GIT_COMMIT
    value: $(Build.SourceVersion)
  - name: BUILD_URI
    value: '$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'

steps:
- script: |
    dotnet test tests
  displayName: ✅  Test

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -w ${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker publish \
          pacts \
        --consumer-app-version ${GIT_COMMIT} \
        --branch ${GIT_BRANCH} \
        --build-url ${BUILD_URI}
  displayName: ✉️  Publish Pacts
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker can-i-deploy \
        --pacticipant ${PACTICIPANT} \
        --version ${GIT_COMMIT} \
        --to-environment production \
    	  --retry-while-unknown 5 \
    	  --retry-interval 10
  displayName: 🎛  Can I deploy?
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker record_deployment \
          --pacticipant ${PACTICIPANT} \
          --version ${GIT_COMMIT} \
          --environment production
  displayName: 🚀  Deploy
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)