# TODO

# name: "record-deployment"
# description: "Record deployment of an application to an environment"
parameters:
  - name: broker_url # "The url of your pact broker"
  - name: token # "Your pact broker token (required for PactFlow)"
    default: ""
  - name: username # "Your pact broker username"
    default: ""
  - name: password # "Your pact broker password"
    default: ""
  - name: application_name # "The name of your application (usually project name)"
    default: false
  - name: environment # "The name of the environment that the pacticipant version was deployed to"
    default: ""
  - name: version # "The version of your application (defaults to version of the code where the action is run from)"
    default: ""
  - name: application_instance # "The application instance to which the deployment has occurred 
    # a logical identifer required to differentiate deployments when there are multiple instances of the same application in an environment."
    default: ""
  application_instance:
- script: |
    ./templates/scripts/recordDeployment.sh
  displayName: Record Deployment
  env: 
    PACT_BROKER_BASE_URL: ${{ coalesce(parameters.broker_url, variables.PACT_BROKER_BASE_URL) }}
    PACT_BROKER_TOKEN: ${{ coalesce(parameters.token, variables.PACT_BROKER_TOKEN) }}
    PACT_BROKER_USERNAME: ${{ coalesce(parameters.username, variables.PACT_BROKER_USERNAME) }}
    PACT_BROKER_PASSWORD: ${{ coalesce(parameters.password, variables.PACT_BROKER_PASSWORD) }}
    application_name: ${{ coalesce(parameters.application_name || variables.application_name }}
    environment: ${{ coalesce(parameters.environment || variables.environment }}
    COMMIT: ${{ coalesce(parameters.version, variables.COMMIT) }}
    application_instance: ${{ coalesce(parameters.application_instance || variables.application_instance }}

