steps:
- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker record_deployment \
          --pacticipant ${PACTICIPANT} \
          --version ${GIT_COMMIT} \
          --environment production
  displayName: 🚀  Deploy
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)